### ISSUE TITLE
Error: max-lisp-eval-depth

### ISSUE THREAD

**Issue by seagle0128** [takaxp/org-tree-slide#29]
I am working on Emacs 26.1 with macOS 10.14. While enable `org-tree-slide-mode` and `C->` to move to the next slide in some org files, I got this error without any backtrace. Before I never encountered this issue. I upgraded the package recently. 

If I set `org-tree-slide-skip-outline-level` 0 or 2, everything is Okay. 

```elisp
Entering debugger...
org-outline-level: Lisp nesting exceeds ‘max-lisp-eval-depth’
```

My config:

```elisp
(use-package org-tree-slide
    :functions (org-display-inline-images org-remove-inline-images)
    :bind (:map org-mode-map
                ("C-<f9>" . org-tree-slide-mode))
    :hook ((org-tree-slide-play . (lambda ()
                                    (text-scale-set 4)
                                    (org-display-inline-images)
                                    (read-only-mode 1)))
           (org-tree-slide-stop . (lambda ()
                                    (text-scale-set 0)
                                    (org-remove-inline-images)
                                    (read-only-mode -1))))
    :config
    (org-tree-slide-simple-profile)
    (setq org-tree-slide-skip-outline-level 1)
    (setq org-tree-slide-slide-in-effect nil))
```

**Comment by takaxp** [comment]
Hi!

Some combination of settings would bring such error, I'll check your config in my environment :)

Best,
Takaaki

**Comment by seagle0128** [comment]
Thanks, my all config is https://github.com/seagle0128/.emacs.d. Org config is `lisp/init-org.el`.

**Comment by takaxp** [comment]
Hi.

When you use `(setq org-tree-slide-skip-outline-level 1)` setting, this means any headings will be skipped. For example, if you have the following org file, the every heading will be skipped.

```
* t1
** t2
*** t3
** t4
* t5
* t6
```

When you use `(setq org-tree-slide-skip-outline-level 2)`, then heading t2, t3, t4 will be skipped and only heading t1, t5, and t6 will be displayed. If you intend to skip t2, t3, and t4, then please specify the variable as `2` not `1` because `1` means "nothing will be displayed as a slide".

But the error should be resolved anyhow so that you can specify any values to `org-tree-slide-skip-outline-level`. The fundamental reason why it occurs is that I introduced a functionality like auto display CONTENT view when the slide reached the last slide. In your case, when you reach the last slide, but the slide is the first level (* hoge) and then it will be skipped, and also back to CONTENT view and automatically move to the next slide. This is a complete loop...

**Comment by takaxp** [comment]
I quickly fix the error, so could you please try the latest version? It will be distributed from MELPA probably by tomorrow.

NOTE: I know some unresolved issues regarding `org-tree-slide-skip-outline-level` are still exist. I'm working on it :)

**Comment by takaxp** [comment]
Hi.

I revised the skipping slide algorithm and newly introduced a function to detect availability of each heading. If the buffer has no headings to show as a slide, then `org-tree-slide-mode` will terminate the slideshow even if you try to start the slide show. In such case, a message of "Terminated..." will be shown in mini buffer.

In your case, `(setq org-tree-slide-skip-outline-level 1)` will be the reason the above termination because the setting means actually **skipping all slide**. So could you try further to change the setting after installing the latest version of this package.

Any questions or requests are welcome :)

Best,
Takaaki

**Comment by takaxp** [comment]
Any updates on this?

**Comment by seagle0128** [comment]
I still have This issue.

**Comment by takaxp** [comment]
Have you tried the latest version of this package?

**Comment by seagle0128** [comment]
I am using `org-tree-slide-20181214.800`. While `(setq org-tree-slide-skip-outline-level 1)`, got this error message.

```elisp
[notice] Terminated. Skipped all slides.
```

**Comment by seagle0128** [comment]
Right. Can I do it? I set to 2 and it works fine anyway.

**Comment by takaxp** [comment]
Thank you for checking. Yes. Please use `2` for that use case :)

**Comment by takaxp** [comment]
Good! Probably I should update the docstirng for the variable later to avoid confusions.
And thank you for reporting this issue, this report really helped the improvement of this package :)
If you have any feature requests or some additional problems, feel free to open a new issue.

Best,
Takaaki
