### ISSUE TITLE
I don't understand documentation of "org-tree-slide-slide-in-blank-lines"

### ISSUE THREAD

**Issue by refaelsh** [takaxp/org-tree-slide#64]
I don't understand documentation of "org-tree-slide-slide-in-blank-lines". Can somebody please explain it to me?

**Comment by takaxp** [comment]
If slide-in effect is allowed in your configuration, "org-tree-slide-slide-in-blank-lines" can specify the staring point of the slide-in effect. If the value is high, the content of each slide will move from near to the bottom of the buffer and slide-in effect will take more time since the content will move (up) through longer space in the buffer.

**Comment by refaelsh** [comment]
Oh, now I understand. Thank you very much.
